import type { ITableColumnGroup } from './TableColumnGroup.interface'

export interface IElementStatus {
	name: string
	shortName: string
	isShowMenuBtnInPlanExpenseRow?: boolean
	isShowDeleteBtnInTaskRow?: boolean
	isShowOpenLikeMainBtnInTaskRow?: boolean
	isShowExpenseCreateMenuAtControlHead?: boolean
	isShowTaskCreateMenuAtControlHead?: boolean
	isShowPlanElementByDefault?: boolean
	isShowFactElementByDefault?: boolean
	isCreateFactElementAfterSelectedThisStatus?: boolean
	admissibleStatuses?: IElementStatus[]
	tableColumnGroup: ITableColumnGroup
	admissibleTableColumnGroups?: ITableColumnGroup[]
	isExpensePlanCreateForbidden?: boolean
	isExpensePlanUpdateForbidden?: boolean
	isExpensePlanDeleteForbidden?: boolean
	isExpenseFactCreateForbidden?: boolean
	isExpenseFactUpdateForbidden?: boolean
	isExpenseFactDeleteForbidden?: boolean
	isExpenseDayGraphPlanCreateForbidden?: boolean
	isExpenseDayGraphPlanUpdateForbidden?: boolean
	isExpenseDayGraphPlanDeleteForbidden?: boolean
	isExpenseDayGraphFactCreateForbidden?: boolean
	isExpenseDayGraphFactUpdateForbidden?: boolean
	isExpenseDayGraphFactDeleteForbidden?: boolean
	isExpenseDateGraphPlanCreateForbidden?: boolean
	isExpenseDateGraphPlanUpdateForbidden?: boolean
	isExpenseDateGraphPlanDeleteForbidden?: boolean
	isExpenseDateGraphFactCreateForbidden?: boolean
	isExpenseDateGraphFactUpdateForbidden?: boolean
	isExpenseDateGraphFactDeleteForbidden?: boolean
	isTaskPlanCreateForbidden?: boolean
	isTaskPlanUpdateForbidden?: boolean
	isTaskPlanDeleteForbidden?: boolean
	isTaskFactCreateForbidden?: boolean
	isTaskFactUpdateForbidden?: boolean
	isTaskFactDeleteForbidden?: boolean
	isTaskDayGraphPlanCreateForbidden?: boolean
	isTaskDayGraphPlanUpdateForbidden?: boolean
	isTaskDayGraphPlanDeleteForbidden?: boolean
	isTaskDayGraphFactCreateForbidden?: boolean
	isTaskDayGraphFactUpdateForbidden?: boolean
	isTaskDayGraphFactDeleteForbidden?: boolean
	isTaskDateGraphPlanCreateForbidden?: boolean
	isTaskDateGraphPlanUpdateForbidden?: boolean
	isTaskDateGraphPlanDeleteForbidden?: boolean
	isTaskDateGraphFactCreateForbidden?: boolean
	isTaskDateGraphFactUpdateForbidden?: boolean
	isTaskDateGraphFactDeleteForbidden?: boolean
}
